name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: |
          # 如果你有自己的构建命令，请替换下面这行
          # 这里简单地把仓库中除 .git 外的所有内容复制到 public 目录
          mkdir -p public
          find . -maxdepth 1 -mindepth 1 ! -name "public" ! -name ".git" -exec cp -R {} public \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
